### ISSUE TITLE
using proxy-middleware fails.

### ISSUE THREAD

**Issue by scottbert** [AveVlad/gulp-connect#166]
Pre 3.x I had the following middlewares specified:
```javascript
middleware: function (server) {
        return [
            connectLivereload({
                port: 35729
            }),
            proxyMiddleware(proxyOptions)
        ];
    }
```
The proxy route is / (I'm proxying my express server, appending the livereload snipped to the HTML on the way through.)
So express = localhost:5000, localhost:9000 is express + LR snippet proxied through to port 9000 via gulp-connect and the proxy-middleware module.

Pre 3, this worked beautifully. Post 3, whenever I visit / I get sent to a directory listing of the directory I ran the gulp script from. Its like gulp-connect is now overriding with a default. If I change my proxy route to something other than '/' and visit it works.

What am I doing wrong?

Full code:
```javascript
function makeServer() {
    var gulpConnect = require('gulp-connect');
    var connectLivereload = require('connect-livereload');
    var proxyMiddleware = require('proxy-middleware');
    var port = process.env.DEV_SERVER_PORT;
    var proxyOptions = url.parse(APP_SERVER);
    proxyOptions.route = '/app';
    gulpConnect.server({
        port,
        middleware: function (server) {
            return [
                connectLivereload({
                    port: 35729
                }),
                proxyMiddleware(proxyOptions)
            ];
        }
    });
    console.log('server http://localhost:' + port);
}
```

**Comment by GregDracoulis** [comment]
Looks like this is a duplicate of #163, seems like a lot of people are having this problem. I don't think it has anything to do with your use of `proxy-middleware`

**Comment by justinmchase** [comment]
There was a bug that was just fixed with middleware being initialized in the wrong order. Can you try this again and let me know if this is still affecting you please?

**Comment by scottbert** [comment]
Yep, that appears to all work, thanks!

**Comment by galtalmor** [comment]
For me there's still an issue when I set `livereload: true`.
When it's `false` it seem to work fine now.
